- hosts: all
  tasks:
    - name: Configuring Docker Repository
      yum_repository:
        name: docker
        description: docker yum repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no

    - name: Installing docker
      package:
         name: "docker-ce-3:18.09.1-3.el7"
         state: present

    - name: Starting Docker Services 
      service:
        name: "docker"
        state: started
        enabled: yes

    - name: Installing python3
      package:
        name: "python36"
        state: present

    - pip:
        name: "docker-py"

    - name: Pull an image
      docker_image:
        name: "httpd"
        source: pull

    - name: Creating directory
      file:
        path: /mywebserver
        state: directory

    - name: Copying HTML
      copy:
        src: "index.html"                  
        dest: "/mywebserver/"            

    - name: Copying Images
      copy:
        src: "redhat.png"                  
        dest: "/mywebserver/" 

    - name: Create a httpd container
      docker_container:
        name: httpd-apache-server
        image: "httpd"
        volumes:
        -  /mywebserver:/usr/local/apache2/htdocs/
        exposed_ports:
        -  "80"
        ports:
        -  "8888:80"

